#!/bin/sh
# Load hosted Pilot env into the process, then start the Expo dev client.
# Does not modify .env.local (local simulator stays on 127.0.0.1).
#
# The env file must NOT live at the project root as `.env*`.
# Expo Metro's virtual `/expo/virtual/env.js` does
# `require.context(<projectRoot>, false, /^\.\/\.env/)` and treats
# `*.local` as a JS source extension. A root `.env.pilot.local` is then
# bundled as JavaScript and Babel fails on `#` comments.
#
# In development, that same virtual module merges
# `{ ...process.env, ...dotEnvFiles }` and `.env.local` wins over the
# shell. Physical-device Metro would then call 127.0.0.1 on the iPhone.
# This script writes a temporary `.env.development.local` (last in Expo's
# merge list) so hosted Pilot values win for this session only.

set -e

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/scripts/.env.pilot.local"
LEGACY_ROOT_ENV="$ROOT/.env.pilot.local"
PILOT_DEV_ENV="$ROOT/.env.development.local"
MARKER="# Generated by start-pilot-device.sh. Do not edit. Deleted when Metro exits."

if [ -f "$LEGACY_ROOT_ENV" ]; then
  echo "Found project-root .env.pilot.local." >&2
  echo "Move it to scripts/.env.pilot.local — Expo Metro bundles root .env* files matching *.local as JS modules." >&2
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  echo "Missing scripts/.env.pilot.local. Copy .env.pilot.example there and fill hosted publishable values." >&2
  exit 1
fi

if grep -Eq '127\.0\.0\.1|localhost' "$ENV_FILE"; then
  echo "Pilot device env must not point at localhost or 127.0.0.1." >&2
  exit 1
fi

if [ -f "$PILOT_DEV_ENV" ] && ! grep -Fq "$MARKER" "$PILOT_DEV_ENV"; then
  echo "Found an existing .env.development.local that this script did not create." >&2
  echo "Move it aside before npm run start:pilot-device." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

if [ -z "${EXPO_PUBLIC_SUPABASE_URL:-}" ] || [ -z "${EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY:-}" ]; then
  echo "EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY are required in scripts/.env.pilot.local." >&2
  exit 1
fi

case "$EXPO_PUBLIC_SUPABASE_URL" in
  https://*.supabase.co|https://*.supabase.co/*) ;;
  *)
    echo "EXPO_PUBLIC_SUPABASE_URL must be an https://*.supabase.co hosted Pilot URL." >&2
    exit 1
    ;;
esac

{
  echo "$MARKER"
  echo "# Overrides simulator .env.local values for Expo virtual env during this session."
  grep -E '^EXPO_PUBLIC_' "$ENV_FILE"
} > "$PILOT_DEV_ENV"

if grep -E '^EXPO_PUBLIC_' "$PILOT_DEV_ENV" | grep -Eq '127\.0\.0\.1|localhost'; then
  rm -f "$PILOT_DEV_ENV"
  echo "Refusing to write a localhost URL into .env.development.local." >&2
  exit 1
fi

cleanup() {
  rm -f "$PILOT_DEV_ENV"
}
trap cleanup EXIT INT TERM

echo "Pilot Metro env loaded (hosted EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY are set)."
echo "Wrote temporary .env.development.local so .env.local cannot pin the iPhone to 127.0.0.1."

# Do not pass the env filename to Expo/Metro. Values are already in the process.
npx expo start --dev-client --clear
