import type { AppCopy } from "./types";

export const copy: AppCopy = {
  tabs: {
    today: "Сегодня",
    treatment: "Лечение",
    diary: "Дневник",
  },
  today: {
    title: "Сегодня",
    loading: "Загрузка…",
    noActiveTreatment: "Сейчас нет активного лечения.",
    noActionsForToday: "На сегодня в приложении нет доступных действий.",
    periodDayLabel: "День",
    tasksLabel: "Задачи на сегодня",
    loadError: "Не удалось загрузить данные.",
    retry: "Повторить",
    markComplete: "Отметить выполненным",
    markIncomplete: "Снять отметку",
    fillDiary: "Заполнить дневник",
    addPhoto: "Добавить фото",
    photoAdded1: "Фото добавлено: 1 из 3",
    photoAdded2: "Фото добавлено: 2 из 3",
    photoAdded3: "Добавлено 3 из 3 фото",
  },
  diary: {
    title: "Дневник",
    loading: "Загрузка…",
    noActiveTreatment: "Сейчас нет активного лечения.",
    loadError: "Не удалось загрузить данные.",
    retry: "Повторить",
    painLabel: "Боль",
    swellingLabel: "Отёк",
    wellbeingLabel: "Самочувствие",
    wellbeingBetter: "Лучше",
    wellbeingUnchanged: "Без изменений",
    wellbeingWorse: "Хуже",
    submit: "Отправить",
    completedToday: "Дневник за сегодня заполнен.",
    entriesLabel: "Записи",
  },
  treatment: {
    title: "Лечение",
    loading: "Загрузка…",
    noActiveTreatment: "Сейчас нет активного лечения.",
    loadError: "Не удалось загрузить данные.",
    retry: "Повторить",
    periodDayLabel: "День",
    emptyMilestones: "Пока нет визитов в ходе лечения.",
    back: "Назад",
    milestoneDetailTitle: "Этап лечения",
    milestoneNotFound: "Этот этап лечения не найден.",
    doctorPhotosLabel: "Фотографии визита",
    doctorPhotosEmpty: "Пока нет фотографий этого визита.",
    doctorPhotosUnavailable: "Не удалось загрузить фотографии.",
    doctorPhotoAccessibilityLabel: "Фотография визита",
  },
  appointment: {
    label: "Ближайшая запись",
    empty: "Ближайшая запись пока не указана.",
  },
  clinicContact: {
    label: "Связь с клиникой",
    unavailable: "Контакт клиники пока недоступен.",
    call: "Позвонить в клинику",
    email: "Написать на почту",
    book: "Записаться",
    openError: "Не удалось открыть контакт.",
  },
  completion: {
    title: "Лечение завершено",
    body: "Лечение отмечено как завершённое. При необходимости свяжитесь с клиникой.",
    loading: "Загрузка…",
    loadError: "Не удалось загрузить данные.",
    retry: "Повторить",
    notCompleted: "Сейчас нет завершённого лечения.",
    surveyTitle: "Отзыв о приложении",
    usefulnessLabel: "Насколько полезным было приложение?",
    clarityLabel: "Я понимал, что нужно делать",
    submit: "Отправить отзыв",
    submitted: "Спасибо за отзыв.",
  },
  access: {
    loading: "Загрузка…",
    authenticationRequired: {
      title: "Доступ выдаёт клиника",
      body: "Это приложение не регистрирует пациентов самостоятельно. Доступ выдаёт клиника по приглашению.",
    },
    serviceUnavailable: {
      title: "Сервис временно недоступен",
      body: "Сейчас не удалось открыть доступ. Попробуйте позже.",
    },
  },
  photos: {
    title: "Фото",
    takePhoto: "Камера",
    chooseFromLibrary: "Галерея",
    confirm: "Добавить",
    retry: "Выбрать снова",
    back: "Назад",
    permissionDenied: "Нет доступа к камере или фотоплёнке.",
    cameraUnavailable: "Камера недоступна на этом устройстве.",
    confirmError: "Не удалось сохранить фото.",
    invalidSource: "Этот файл нельзя добавить.",
    dailyCap: "Сегодня уже добавлено 3 фото.",
    noActiveTreatment: "Сейчас нет активного лечения.",
  },
};
